# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExpreRegu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExpresionRegular(object):
    def setupUi(self, ExpresionRegular):
        ExpresionRegular.setObjectName("ExpresionRegular")
        ExpresionRegular.resize(598, 426)
        self.gridLayout = QtWidgets.QGridLayout(ExpresionRegular)
        self.gridLayout.setObjectName("gridLayout")
        self.btnEvaluarExpre = QtWidgets.QPushButton(ExpresionRegular)
        self.btnEvaluarExpre.setObjectName("btnEvaluarExpre")
        self.gridLayout.addWidget(self.btnEvaluarExpre, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(ExpresionRegular)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.txtListaPalabras = QtWidgets.QLineEdit(ExpresionRegular)
        self.txtListaPalabras.setObjectName("txtListaPalabras")
        self.horizontalLayout_4.addWidget(self.txtListaPalabras)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ExpresionRegular)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(ExpresionRegular)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txtExpresionRegu = QtWidgets.QLineEdit(ExpresionRegular)
        self.txtExpresionRegu.setObjectName("txtExpresionRegu")
        self.horizontalLayout.addWidget(self.txtExpresionRegu)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(ExpresionRegular)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.txtResultadoExpreRegu = QtWidgets.QPlainTextEdit(ExpresionRegular)
        self.txtResultadoExpreRegu.setObjectName("txtResultadoExpreRegu")
        self.horizontalLayout_5.addWidget(self.txtResultadoExpreRegu)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)

        self.retranslateUi(ExpresionRegular)
        QtCore.QMetaObject.connectSlotsByName(ExpresionRegular)

    def retranslateUi(self, ExpresionRegular):
        _translate = QtCore.QCoreApplication.translate
        ExpresionRegular.setWindowTitle(_translate("ExpresionRegular", "Dialog"))
        self.btnEvaluarExpre.setText(_translate("ExpresionRegular", "Evaluar"))
        self.label_3.setText(_translate("ExpresionRegular", "Listado de palabras (separar por , ) = "))
        self.label.setText(_translate("ExpresionRegular", "Expresión regular"))
        self.label_2.setText(_translate("ExpresionRegular", "Patrón o rexpresión regular ="))
        self.label_4.setText(_translate("ExpresionRegular", "Resultado = "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExpresionRegular = QtWidgets.QDialog()
    ui = Ui_ExpresionRegular()
    ui.setupUi(ExpresionRegular)
    ExpresionRegular.show()
    sys.exit(app.exec_())
