# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vAEFD.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vAEFD(object):
    def setupUi(self, vAEFD):
        vAEFD.setObjectName("vAEFD")
        vAEFD.resize(1046, 708)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(vAEFD)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(vAEFD)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.vista = QtWidgets.QGraphicsView(vAEFD)
        self.vista.setObjectName("vista")
        self.verticalLayout.addWidget(self.vista)
        self.BtnCrearEstado = QtWidgets.QPushButton(vAEFD)
        self.BtnCrearEstado.setObjectName("BtnCrearEstado")
        self.verticalLayout.addWidget(self.BtnCrearEstado)
        self.BtnAgregarTransicion = QtWidgets.QPushButton(vAEFD)
        self.BtnAgregarTransicion.setObjectName("BtnAgregarTransicion")
        self.verticalLayout.addWidget(self.BtnAgregarTransicion)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(vAEFD)
        QtCore.QMetaObject.connectSlotsByName(vAEFD)

    def retranslateUi(self, vAEFD):
        _translate = QtCore.QCoreApplication.translate
        vAEFD.setWindowTitle(_translate("vAEFD", "Dialog"))
        self.label.setText(_translate("vAEFD", "Simulador autómata de estados finitos deterministicos "))
        self.BtnCrearEstado.setText(_translate("vAEFD", "Crear estado"))
        self.BtnAgregarTransicion.setText(_translate("vAEFD", "Agregar transición"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vAEFD = QtWidgets.QDialog()
    ui = Ui_vAEFD()
    ui.setupUi(vAEFD)
    vAEFD.show()
    sys.exit(app.exec_())
